### ISSUE TITLE
Temporal and spatial dimension names

### ISSUE THREAD

**Issue by Loisel** [pik-piam/mrcommons#21]
In a recent PR #19 the column names of the temporal and spatial dimension names in the dataset `GDPppp` changed when not aggregating the dataset, i.e., upon calling `mrremind::calcOutput("GDPppp", aggregate=F)`. The old names have been `Year` and `ISO3`, respectively, the new ones are `period` and `region`.
- This breaks code for EDGE-T and possibly other *external* libraries.
- It is misleading to use the label `region` for ISO country codes, since regional mapping explicitly map between a REMIND/MagPIE `region` and `ISO` countries. A `merge(data, mapping)` would then just work, but would not do what you expect.
- I second standardization, but at the moment, e.g., `Population` is shipped as
```
> str(str(calcOutput("Population", aggregate = F)))

Run calcOutput(type = "Population", aggregate = FALSE)
~  - loading cache calcPopulation-FfingerprintError.rds
Exit calcOutput(type = "Population", aggregate = FALSE) in 0.37 seconds
Formal class 'magpie' [package "magclass"] with 1 slot
  ..@ .Data: num [1:249, 1:38, 1:10] 0.05736 9.93841 6.2033 0.00611 0.02098 ...
  .. ..- attr(*, "dimnames")=List of 3
  .. .. ..$ iso2c   : chr [1:249] "ABW" "AFG" "AGO" "AIA" ...
  .. .. ..$ year    : chr [1:38] "y1965" "y1970" "y1975" "y1980" ...
  .. .. ..$ variable: chr [1:10] "pop_SSP1" "pop_SSP2" "pop_SSP3" "pop_SSP4" ...
```
so here we still use `iso2c` and `year`. I would suggest, *if* we want to standardize these, we maybe would do all of them.

**Comment by johanneskoch94** [comment]
Yes we absolutely should standardize them all at the same time. Just to make it clear, we did not try and do this yet. The question now is do you need an immediate fix on the mrcommons side? Or can it wait for mrdrivers to be integrated? Could the temporary fix be included in EDGE-T?

**Comment by johanneskoch94** [comment]
@MariannaR Ok so I'm making a statement, and if Lavinia doesn't contradict me then it shall be valid :) GDP, Pop, GDPpc, and Urbanisation scenarios, as returned by mrcomons and in future by mrdrivers, shall carry the set names: "iso3c", "year" and "variable". (It shall be so because "iso3c" corresponds to the name of the country-codons used, and is not "region". :) ) 

However you haven't answered my questions, do you need an immediate fix on the mrcommons side? Because if so, I need some time check if nothing ELSE breaks ;). Couldn't it be possible to just rename the set names now at the interface to edgeTransport? Similar to https://github.com/pik-piam/mrremind/blob/b093b6e27f4af3f1633efaa2a2635f56d84c4c7d/R/calcEDGETrData.R#L30-L40 ? I mean I know that obviously that wasn't enough, but maybe we can fix it at the other interfaces?

**Comment by Loisel** [comment]
No an immediate fix is not needed, we can of course patch this thing temporarily :+1:
I just want to avoid a lot of back and forth, that's why it would be nice to change it only once afterwards and have no other surprises.

**Comment by johanneskoch94** [comment]
ok great! and thank you! I will let you know once the set names are changed.
